### PR TITLE
Docs/lists to list

### PR DESCRIPTION
**Pull request by domenkozar**
Renames

```
import Material.List as Lists
```
to
```
import Material.List as List
```

Now it's consistent with the rest of the demos. Note that I haven't renamed the file itself.

cc @debois

### CODE REVIEW

**Comment by debois** [comment]
Thanks, really appreciate it!

I'm a bit concerned there'll be confusion with `List` from core, though—this is why I used `Lists` in the first place. But maybe I'm overly cautious. @aforemny, @vipentti, any thoughts?

**Comment by aforemny** [comment]
Given that fact that we are importing `module Material.Lists as Lists` I think it is the right way to go.

**Comment by OvermindDL1** [comment]
@aforemny Are there any name clashes though?

Remember that if you import multiple modules into the same name in Elm it all 'just works' because each name in that module is unique.  If you have multiple functions with the same name then the compiler will yell at you only if that function is used, at which point you just have to be explicit to the module it belongs to.  I don't think Material.List has or could even have any overlapping function names with the stock List module.

**Comment by debois** [comment]
Since the Demo is used quite often by sometimes newbie users as guidance, conceivably someone will at some point be confused about what `List` means exactly. For that reason, I'm closing this without merging. 

@domenkozar: I'm really sorry we couldn't take this—I do hope you'll keep them coming regardless!

**Comment by domenkozar** [comment]
@debois no worries. I'll leave the branch alive if this comes up again to be reconsidered. Thanks!

**Pull request closed without merging**
