### PR TITLE
Textfield extra attributes

### PR DESCRIPTION
**Pull request by vipentti**
Had some time on my hands so added some attributes that were discussed in #87.

 ```elm
  , Textfield.render MDL [6] model.mdl
      [ Textfield.label "Default multiline textfield (50 char limit)"
      , Textfield.textarea
      , Textfield.autofocus -- New 
      , Textfield.maxlength 50 -- New
      , Textfield.onBlur (Blur [6]) -- New
      , Textfield.onFocus (Focus [6]) -- New
      ]

```

### CODE REVIEW

**Comment by debois** [comment]
Very good thanks. Feel like updating the Demo to somehow showcase onBlur/onFocus, maybe add a slider to set maxlength, and maybe add code samples to everything? (It's ok to say no, in that case, I'll just merge this.)

**Comment by vipentti** [comment]
I'll see what I can do to update the demos a bit.

There should be samples for all options except for table-striped and no-wrap I believe.

**Comment by vipentti** [comment]
Added a better maxlength demo with a slider to increase and decrease the maxlength. 

Also removed some incorrect documentation..

Unfortunately, could not come up with a demo for onFocus and onBlur

**Comment by debois** [comment]
Cool, thanks.

**Comment by debois** [comment]
This PR gave us custom handlers on Textfield, but it turned out to be at the price of ripples on Firefox. (We love you, Firefox.) I think that's a bad tradeoff for the v7 branch. Can we revert it?

**Comment by vipentti** [comment]
I assume you mean focus and blur on firefox ?

**Comment by debois** [comment]
Sorry, yes. To be precise: Without a major version bump, we have to chose at most one of: 

- Fix #166 (textfield doesn't react to focus/blur on Firefox)
- Fix #87 (more user-exposed event handlers for textfield)

I think #166 is way more important, so I'd like to revert this PR; or at least somehow fix #166 at the cost of losing functionality of #87 on Firefox.

We'll get back #87 eventually in master (and so v8) when we merge #179 (custom event handlers).

**Comment by vipentti** [comment]
@debois I think I may have a fix for #166  that will break #87 on Firefox (onBlur and onFocus)

**Pull request merged**
