### PR TITLE
Add Dialog Component

### PR DESCRIPTION
**Pull request by puhrez**
Address #52 

- [x] Module written
- [ ] Demo written
- [x] Docs written
- [ ] Enforce "mdl-dialog__actions--full-width" only for Actions

### CODE REVIEW

**Comment by puhrez** [comment]
Having problem viewing the

**Comment by debois** [comment]
Awesome, thanks!

**Comment by debois** [comment]
I don't think we need to enforce `fullWidth` only for actions, for a couple reasons: 

1. It's not dangerous. You add it the wrong place, worst thing that happens is you get slightly off layout. It might even work. 
2. It's difficult to enforce without going into very restrictive APIs. 
3. There's plenty of other examples in the library where we are lax with options. 

I did update the docs to make clear it belongs on action.

**Comment by debois** [comment]
I added a new issue #126 for improving the demo. This ticks off your last box :)

**Pull request merged**
