### PR TITLE
Added reference implementation for Offtie.com

### PR DESCRIPTION
**Pull request by hakonrossebo**

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Is there a source link for it to use as a reference?

**Comment by hakonrossebo** [comment]
I didn't get the source reference when I got the reply on the elm-discuss group - to me it looks like that the author wants to keep this private. I'm not sure whats best - should we try to keep the references here only when the source is available?

**Comment by debois** [comment]
If there's any doubts whether the author wants to be on the list, let's keep it off. We don't want to antagonise anybody.

**Comment by hakonrossebo** [comment]
I was a bit unclear - I just meant that the author didn't share the source code - He suggested this site by himself on elm-discuss

**Comment by debois** [comment]
Ok. Maybe just ask on elm-discuss if he wants to share the source?

**Comment by OvermindDL1** [comment]
He released the source:  https://bitbucket.org/gladimdim/offtieweb/src
Via:  https://groups.google.com/forum/#!topic/elm-discuss/if3gYlT-H2k

**Comment by hakonrossebo** [comment]
I only had this edited online. Followed GitHub merge PR command line instructions and this created a separate PR #222.

**Pull request closed without merging**
